### ISSUE TITLE
Issue with npm run watch

### ISSUE THREAD

**Issue by moafzalmulla** [krzysztofsopa/react-redux-node-authentication#1]
Hi there, 

Great repo, just some issues I faced.

I follow installation instructions but it throws error.

I had to also install react and react-dom separately as modules werent found

See screenshot
![screen shot 2018-03-02 at 15 40 37](https://user-images.githubusercontent.com/2478550/36907378-66aba1f0-1e30-11e8-8608-514104648601.png)

**Comment by krzysztofsopa** [comment]
Hi @tweetzal,

Thanks for testing it out!

I updated dependencies and description how to install this project. I tested it locally - I am using mac  - and it works as expected. Hopefully it will resolve also your issues.

If you will find any more problems just let me know!

**Comment by moafzalmulla** [comment]
Cool Thanks

I did another clone but keep getting this - see screenshot

Any idea what I could be missing ?

Thanks again
<img width="298" alt="screen shot 2018-03-05 at 18 20 26" src="https://user-images.githubusercontent.com/2478550/36992157-fb5dd228-20a1-11e8-920d-f144832bdd5e.png">

**Comment by krzysztofsopa** [comment]
Hi,
 
I updated one more time readme. I cannot reproduce your situation but it looks like you are trying to run front app not from dist folder but from different location.

**Comment by moafzalmulla** [comment]
Brillant! It works 

I suggest you update docs to say : 

Go to dist folder and in a new terminal tab run:

`$ live-server --entry-file=index.js //in new terminal tab`

Just makes it easier to understand, but other than that great repo.
Would be great to see a react-bootstrap version :)
